version: "3"
services:
  client:
    image: "rgomezrx/multi-client"
    hostname: client
    mem_limit: 128m
  server:
    image: "rgomezrx/multi-server"
    hostname: "api"
    mem_limit: 128m
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
    image: "rgomezrx/multi-worker"
    hostname: worker
    mem_limit: 128m
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: "rgomezrx/multi-nginx"
    hostname: nginx
    mem_limit: 128m
    ports:
      - "80:80"
